CREATE TABLE BOTTLES(
   ID INTEGER PRIMARY KEY   AUTOINCREMENT,
   BRAND           TEXT         NOT NULL,
   PRICE           DECIMAL(5,2) NOT NULL,
   VOLUME		   INTEGER      NOT NULL,
   COUNT		   INTEGER      NOT NULL
);

INSERT INTO BOTTLES (BRAND,PRICE,VOLUME,COUNT)
VALUES ('La Goudale',1.90,33,20 );

INSERT INTO BOTTLES (BRAND,PRICE,VOLUME,COUNT)
VALUES ('Kasteel Triple',2.80,33,45 );



CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY   AUTOINCREMENT,
    NAME           TEXT    NOT NULL,
    ROLE           TEXT    NOT NULL,
    PASSWORD       TEXT    NOT NULL
);

INSERT INTO USERS (NAME,ROLE, PASSWORD)
VALUES ('admin','ADMIN', 'admin123');

INSERT INTO USERS (NAME,ROLE, PASSWORD)
VALUES ('client','CLIENT', 'client123');